### ISSUE TITLE
 I reported an error when trying to run the first use case. 

### ISSUE THREAD

**Issue by RANYABING** [AICPS/roadscene2vec#12]
I reported an error when trying to run the first use case. Does this problem exist in a specific version of networkx?
pytorch==1.10.0
cudatoolkit==11.3.1
networkx==2.6.3

The following is error infomation:
(av) ranyabing@ranyabing:~/roadscene2vec/examples$ python use_case_1.py 
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/it]
  0%|                                                                                                          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ranyabing/roadscene2vec/examples/use_case_1.py", line 35, in <module>
    visualize(scenegraph_extraction_config) #visualize extracted scenegraphs
  File "/home/ranyabing/roadscene2vec/roadscene2vec/util/visualizer.py", line 172, in visualize
    visualize_real_image(extraction_config)
  File "/home/ranyabing/roadscene2vec/roadscene2vec/util/visualizer.py", line 192, in visualize_real_image
    draw(extractor, sequence[frame], bbox, bev, sg, save_path='output.png')
  File "/home/ranyabing/roadscene2vec/roadscene2vec/util/visualizer.py", line 131, in draw
    sg_img = draw_scenegraph_pydot(sg)
  File "/home/ranyabing/roadscene2vec/roadscene2vec/util/visualizer.py", line 105, in draw_scenegraph_pydot
    A = nx_pydot.to_pydot(sg)
  File "/home/ranyabing/anaconda3/envs/av/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 263, in to_pydot
    raise ValueError(
ValueError: Node names and attributes should not contain ":" unless they are quoted with "".                For example the string 'attribute:data1' should be written as '"attribute:data1"'.                Please refer https://github.com/pydot/pydot/issues/258

**Comment by malawada** [comment]
Ok great, could you please link the solution you found? It may help others who run into the same issue. Thanks.
